version: '3'
services:
  db:
    image: postgres:17.5
    container_name: "pisco-db"
    volumes:
      - db-data:/usr/local/share/postgresql/data
      - ./:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
volumes:
  db-data:
    driver: local